### ISSUE TITLE
Provide examples, test vectors, etc.

### ISSUE THREAD

**Issue by nealmcb** [c2pa-org/specifications#16]
Where can we find data to use in testing implementations of the spec? JUMBF files of various formats, other media files with embedded C2PA data, test vectors, associated credentials and keys, invalid examples, etc? I haven't found them in the public specification files.

**Comment by lrosenthol** [comment]
https://github.com/c2pa-org/public-testfiles is where we will be keeping a set of public test files (both pass and fail) for folks to work from!
