### ISSUE TITLE
Embedded environments without timestamp support need a way to have durable manifests

### ISSUE THREAD

**Issue by mauricefisher64** [c2pa-org/specifications#23]
Some devices like camera may not have access to time.  Without this the manifest they generate will lack a timestamp.  Without a timestamp their manifests will ultimately fail the certificate validity test when the certificates expire.  They are looking for a way to have durable manifests without the timestamp requirement.

**Comment by mauricefisher64** [comment]
Moved to spec-core

**Comment by 7thias** [comment]
This issue seems interesting. What is spec-core and where can I view it?
