### ISSUE TITLE
Enhance Accessibility to GitHub Pages Specifications

### ISSUE THREAD

**Issue by thatvideoshopguy** [c2pa-org/specifications#35]
I noticed that navigating to the [specifications hosted on GitHub Pages](https://c2pa.org/specifications/specifications/1.3/index.html) could be a bit more streamlined. Currently, it requires an unnecessary amount of time to find the specifications page from the repository.

To enhance the user experience and improve the efficiency of navigation, I suggest adding a direct link to the specifications page within the README or under the short description. This would enable contributors and users to quickly access the relevant information they need.

Thank you for considering this improvement.

**Comment by lrosenthol** [comment]
@thatvideoshopguy Thanks for the suggestion!   Will do!!
