### ISSUE TITLE
link relation registration

### ISSUE THREAD

**Issue by martinthomson** [c2pa-org/specifications#38]
rel=c2pa-manifest is defined [here](https://c2pa.org/specifications/specifications/1.3/specs/C2PA_Specification.html#_by_reference_or_uri), but it does not follow the advice in [Section 2.1.1.1](https://datatracker.ietf.org/doc/html/rfc8288#section-2.1.1.1) of the (linked) RFC.  The relation type should be registered.

**Comment by lrosenthol** [comment]
This has been completed - we are officially registered!
