### ISSUE TITLE
The CAWG says FCC, Ad-ID, EIDR, are a Gathered Conundrum

### ISSUE THREAD

**Issue by arosenMS** [c2pa-org/specifications#48]
The professional assertion ball has returned to the C2PA side of the net. It is my sad duty to report that the consensus of the CAWG, led by Eric Scouten, John Collomosse, and others is that all gathered assertions are not subject to a conformance or compliance certification. Therefore, it falls to the C2PA TWG to ensure that, in the name of interoperability, the value of trustworthy registrations from officially recognized professional organizations receives the utmost regard by common validation tool implementations.
Even though local broadcasters are resolute regarding the supremacy of their licensed call letters, the CAWG wants to keep ownership out of their remit. Failure to convey absolute respect for certain specific gathered assertions will cause conflict with the ubiquitous newsroom automation systems that implement [NDR](https://doi.org/10.5594/M001710). Implementations that do not reflect the possessiveness surrounding these registered business personhood values will also cause various other types of industry harm.

**Comment by lrosenthol** [comment]
C2PA supports this direction as something that is important to our overall use cases.  However, TWG would like those relevant industries to take on responsibility for defining the specifics.
