### ISSUE TITLE
does a validator care about the end/serving URL in the case of External Data Validation

### ISSUE THREAD

**Issue by Brianthered** [c2pa-org/specifications#74]
https://github.com/c2pa-org/specifications/blob/153a62110fa0f6a61d4b960509fc50a645c6c2e1/build/site/specifications/2.1/specs/C2PA_Specification.html#L5109

I feel like someone more security minded than I am should think this through, but under the current design, you could have a domain that has the external data for validation on it redirect to a different domain.  I don't know if that is OK.

A usecase in favor of it being ok might be something like a simple http -> https redirect

A usecase that might not be ok would be someone hijacking a domain to misidentify an image as valid when it wasn't.  This seems like a complex attack, and would probably only be worthwhile in some odd circumstances.

**Comment by lrosenthol** [comment]
Ah, you misread this.   

You read URI as URL.  In this case, it is a JUMBF URI to another JUMBF box (the claim signature box) inside the JUMBF structure.  This is also clearly identified in the CDDL grammars.
