### ISSUE TITLE
search doesn't work in prod - https://c2pa.org/specifications/_/css/search.css and  https://c2pa.org/specifications/search-index.js (Not Found)

### ISSUE THREAD

**Issue by Brianthered** [c2pa-org/specifications#83]
Search doesn't work in prod because of:
`https://c2pa.org/specifications/_/css/search.css` and `https://c2pa.org/specifications/search-index.js (Not Found)` in prod

highlight.js is also failing a bunch, I believe, but didn't actually determine for certain, that it is failing because it is missing its css.  The highlight.css doesn't exist, but that may not be why it is broken.

I can see all this in the console on the page: https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html (but looking at other pages, the problem is with the header, so it is a problem regardless of page.  

If someone wants to point me at the build code, I can take a look, but this looks like someone dropped an include somewhere.

**Comment by lrosenthol** [comment]
This is well known and tracked internally at https://github.com/c2pa-org/specs-core/issues/1112
